//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleLab2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicee1")]
    public interface IServicee1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicee1/Add", ReplyAction="http://tempuri.org/IServicee1/AddResponse")]
        Calculator.Complex Add(double a_real, double a_imaginary, double b_real, double b_imaginary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicee1/Add", ReplyAction="http://tempuri.org/IServicee1/AddResponse")]
        System.Threading.Tasks.Task<Calculator.Complex> AddAsync(double a_real, double a_imaginary, double b_real, double b_imaginary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicee1/Multiply", ReplyAction="http://tempuri.org/IServicee1/MultiplyResponse")]
        Calculator.Complex Multiply(double a_real, double a_imaginary, double b_real, double b_imaginary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicee1/Multiply", ReplyAction="http://tempuri.org/IServicee1/MultiplyResponse")]
        System.Threading.Tasks.Task<Calculator.Complex> MultiplyAsync(double a_real, double a_imaginary, double b_real, double b_imaginary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicee1/Substract", ReplyAction="http://tempuri.org/IServicee1/SubstractResponse")]
        Calculator.Complex Substract(double a_real, double a_imaginary, double b_real, double b_imaginary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicee1/Substract", ReplyAction="http://tempuri.org/IServicee1/SubstractResponse")]
        System.Threading.Tasks.Task<Calculator.Complex> SubstractAsync(double a_real, double a_imaginary, double b_real, double b_imaginary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicee1/Divide", ReplyAction="http://tempuri.org/IServicee1/DivideResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Calculator.DivideByZeroException), Action="http://tempuri.org/IServicee1/DivideDivideByZeroExceptionFault", Name="DivideByZeroException", Namespace="http://schemas.datacontract.org/2004/07/Calculator")]
        Calculator.Complex Divide(double a_real, double a_imaginary, double b_real, double b_imaginary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicee1/Divide", ReplyAction="http://tempuri.org/IServicee1/DivideResponse")]
        System.Threading.Tasks.Task<Calculator.Complex> DivideAsync(double a_real, double a_imaginary, double b_real, double b_imaginary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicee1Channel : ConsoleLab2.ServiceReference1.IServicee1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Servicee1Client : System.ServiceModel.ClientBase<ConsoleLab2.ServiceReference1.IServicee1>, ConsoleLab2.ServiceReference1.IServicee1 {
        
        public Servicee1Client() {
        }
        
        public Servicee1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Servicee1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servicee1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Servicee1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Calculator.Complex Add(double a_real, double a_imaginary, double b_real, double b_imaginary) {
            return base.Channel.Add(a_real, a_imaginary, b_real, b_imaginary);
        }
        
        public System.Threading.Tasks.Task<Calculator.Complex> AddAsync(double a_real, double a_imaginary, double b_real, double b_imaginary) {
            return base.Channel.AddAsync(a_real, a_imaginary, b_real, b_imaginary);
        }
        
        public Calculator.Complex Multiply(double a_real, double a_imaginary, double b_real, double b_imaginary) {
            return base.Channel.Multiply(a_real, a_imaginary, b_real, b_imaginary);
        }
        
        public System.Threading.Tasks.Task<Calculator.Complex> MultiplyAsync(double a_real, double a_imaginary, double b_real, double b_imaginary) {
            return base.Channel.MultiplyAsync(a_real, a_imaginary, b_real, b_imaginary);
        }
        
        public Calculator.Complex Substract(double a_real, double a_imaginary, double b_real, double b_imaginary) {
            return base.Channel.Substract(a_real, a_imaginary, b_real, b_imaginary);
        }
        
        public System.Threading.Tasks.Task<Calculator.Complex> SubstractAsync(double a_real, double a_imaginary, double b_real, double b_imaginary) {
            return base.Channel.SubstractAsync(a_real, a_imaginary, b_real, b_imaginary);
        }
        
        public Calculator.Complex Divide(double a_real, double a_imaginary, double b_real, double b_imaginary) {
            return base.Channel.Divide(a_real, a_imaginary, b_real, b_imaginary);
        }
        
        public System.Threading.Tasks.Task<Calculator.Complex> DivideAsync(double a_real, double a_imaginary, double b_real, double b_imaginary) {
            return base.Channel.DivideAsync(a_real, a_imaginary, b_real, b_imaginary);
        }
    }
}
